import { mkdir, readdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { beforeEach, describe, expect, it } from 'vitest';
import { runInit } from '../src/init.js';
import { AGENTS_PARAGRAPH, AUTO_END, LIFECYCLE_WARNING, RULES_TEMPLATE, parsePage } from '../src/wiki.js';
import { ADMIN_URL, adminSql, pagePath, resetFixture, runCli, setFrontmatter, tempRoot } from './helpers.js';

const FIXTURE_PAGES = [
  'public.%4Frders.md',
  'public.audit_events.md',
  'public.customers.md',
  'public.daily_sales.md',
  'public.odd%2Ename%2F%C3%BC%20%22q%22.md',
  'public.order_items.md',
  'public.order_totals.md',
  'public.orders.md',
  'public.page_views.md',
  'public.products.md',
  'public.returns.md',
];

async function listFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true, recursive: true })) {
    if (entry.isFile()) out.push(relative(dir, join(entry.parentPath, entry.name)));
  }
  return out.sort();
}

async function snapshot(root: string): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  for (const f of await listFiles(root)) files.set(f, await readFile(join(root, f), 'utf8'));
  return files;
}

const read = (root: string, f: string) => readFile(join(root, f), 'utf8');
const init = (root: string, extra: Partial<Parameters<typeof runInit>[0]> = {}) => runInit({ root, url: ADMIN_URL, ...extra });

function parsed(text: string, id: string) {
  const p = parsePage(text, id);
  if (!p.ok) throw new Error(p.reason);
  return p.page;
}

describe('tapu init', () => {
  let root: string;

  beforeEach(async () => {
    await resetFixture();
    root = await tempRoot();
  });

  it('creates the expected artifacts', async () => {
    const result = await init(root, { now: new Date('2026-09-25T10:30:00.123Z') });
    expect(await listFiles(root)).toEqual([
      '.tapu/catalog.json',
      '.tapu/config.json',
      'db-wiki/index.md',
      'db-wiki/log.md',
      'db-wiki/rules.md',
      ...FIXTURE_PAGES.map((p) => `db-wiki/tables/${p}`),
    ]);
    expect(await read(root, '.tapu/config.json')).toBe('{"version":1,"schemas":["public"],"wikiDir":"db-wiki"}\n');
    expect(result).toMatchObject({ relations: 11, enums: 4, undocumented: 9, partial: false });
    expect(result.pages.created).toHaveLength(11);
    expect(await read(root, 'db-wiki/log.md')).toBe(
      '# Tapu log\n\n2026-09-25T10:30:00Z init: 11 relations, 4 enums; pages: 11 new, 0 changed, 0 removed, 0 out of scope, 0 skipped\n',
    );

    const catalog = JSON.parse(await read(root, '.tapu/catalog.json'));
    expect(catalog).toMatchObject({ format: 2, coverage: 'tapu-pg-v1', generatedAt: '2026-09-25T10:30:00.123Z', schemas: ['public'] });

    const index = await read(root, 'db-wiki/index.md');
    expect(index).toContain('- [public.orders](tables/public.orders.md) (table) — _undocumented_');
    expect(index).toContain('- [public.customers](tables/public.customers.md) (table) — Registered shop customers');
    expect(index).toContain('(tables/public.%254Frders.md)');
    expect(index).not.toContain('## Archived pages');

    const orders = await read(root, 'db-wiki/tables/public.orders.md');
    expect(orders.startsWith('---\ntapu: 1\ntable: public.orders\npurpose: ""\nowner: ""\ntags: []\ncolumns: {}\n---\n')).toBe(true);
    const page = parsed(orders, 'public.orders');
    expect(page.state).toBe('active');
    expect(page.hash).toBe(catalog.relations.find((r: { id: string }) => r.id === 'public.orders').hash);
    expect(orders).toContain('Generated by tapu init. Edit explanations outside this block.');
    expect(orders).toContain('- public.order_status: pending, paid, shipped, cancelled');
    expect(orders).toContain('- orders_customer_id_fkey: (customer_id) → [public.customers](public.customers.md) (id); on delete no action; on update no action');
    expect(orders).toContain('- [public.order_items](public.order_items.md) (order_id) — order_items_order_id_fkey');
    expect(orders).toContain('- fk_without_index: customer_id');
    expect(orders).toContain('| customer_email | text | no |  | SENSITIVE |  |');
    expect(orders).toContain('WHERE (status = ');
    expect(orders).toContain('## Why it exists');

    const customers = await read(root, 'db-wiki/tables/public.customers.md');
    // External targets keep their identifiers but get no link.
    expect(customers).toContain('→ ext.accounts (not captured) (id)');
    expect(customers).not.toContain('ext.accounts.md');

    const audit = await read(root, 'db-wiki/tables/public.audit_events.md');
    expect(audit).toContain('- no_primary_key');
    expect(audit).toContain('(invalid)');
    expect(audit).not.toMatch(/[\u0007\u001b\r]/);
    expect(parsePage(audit, 'public.audit_events').ok).toBe(true);

    const view = await read(root, 'db-wiki/tables/public.order_totals.md');
    expect(view).toContain('### View definition\n\n     SELECT o.id AS order_id,');
    expect(await read(root, 'db-wiki/tables/public.page_views.md')).toContain('**Partition key:** RANGE (viewed_at)');

    const odd = await read(root, 'db-wiki/tables/public.odd%2Ename%2F%C3%BC%20%22q%22.md');
    expect(odd).toContain('table: "public.\\"odd.name/ü \\"\\"q\\"\\"\\""\n');
    expect(parsePage(odd, 'public."odd.name/ü ""q"""').ok).toBe(true);
  });

  it('writes a rules template that invents no policy, once', async () => {
    await init(root);
    expect(await read(root, 'db-wiki/rules.md')).toBe(RULES_TEMPLATE);
    expect(RULES_TEMPLATE).toContain('An empty section means no convention was supplied.');
    expect(RULES_TEMPLATE).toMatch(/## Naming\n\n## Migrations\n\n## Data handling\n$/);
    await writeFile(join(root, 'db-wiki/rules.md'), 'Our rules.\n');
    await init(root);
    expect(await read(root, 'db-wiki/rules.md')).toBe('Our rules.\n');
    await rm(join(root, 'db-wiki/rules.md'));
    await init(root);
    expect(await read(root, 'db-wiki/rules.md')).toBe(RULES_TEMPLATE);
  });

  it('is idempotent: an unchanged rerun changes only generatedAt and appends a log entry', async () => {
    await init(root, { now: new Date('2026-09-25T10:30:00Z') });
    const first = await snapshot(root);
    const result = await init(root, { now: new Date('2026-09-25T11:00:00Z') });
    const second = await snapshot(root);

    expect([...second.keys()]).toEqual([...first.keys()]);
    for (const [file, text] of second) {
      if (file === '.tapu/catalog.json') {
        expect(text.replace(/"generatedAt": ".*"/, '')).toBe(first.get(file)!.replace(/"generatedAt": ".*"/, ''));
        expect(text).not.toBe(first.get(file));
      } else if (file === 'db-wiki/log.md') {
        expect(text).toBe(
          first.get(file)! +
            '2026-09-25T11:00:00Z init: 11 relations, 4 enums; pages: 0 new, 0 changed, 0 removed, 0 out of scope, 0 skipped\n',
        );
      } else {
        expect(text, file).toBe(first.get(file));
      }
    }
    expect(result.pages).toEqual({ created: [], updated: [], removed: [], outOfScope: [], skipped: [] });
  });

  it('preserves human edits outside the block byte for byte', async () => {
    await init(root);
    const file = pagePath(root, 'public.customers.md');
    const original = await readFile(file, 'utf8');
    const edited = original
      .replace(
        /^---\n[\s\S]*?\n---\n/,
        [
          '---',
          '# Owned by the growth team',
          'owner:   "growth@example.com"   # keep this spacing',
          'tapu: 1',
          'purpose: Everyone who has ever signed up',
          'table: public.customers',
          'tags: [pii, core]',
          'columns:',
          '  email:',
          '    note: "Login identifier; unique"',
          '  emailed_at:',
          '    sensitive: true',
          '  phone: { sensitive: false }',
          '  fax: { note: "dropped in 2024" }',
          'custom_key: {a: 1}   # unknown keys survive',
          '---',
          '',
        ].join('\n'),
      )
      .replace('# public.customers\n', '# public.customers\n\nIntro written by a human.\n')
      .replace('## Notes\n', '## Notes\n\n- 2026-03: decided to keep soft-deleted customers.\n\nTrailing text   \n');
    await writeFile(file, edited);

    await init(root);
    const after = await readFile(file, 'utf8');
    const a = parsed(edited, 'public.customers');
    const b = parsed(after, 'public.customers');
    expect(after.slice(0, b.autoStart)).toBe(edited.slice(0, a.autoStart));
    expect(after.slice(b.autoEnd)).toBe(edited.slice(a.autoEnd));

    // The block honours both override values.
    expect(after).toContain('| emailed_at | timestamp with time zone | yes |  | SENSITIVE |  |');
    expect(after).toContain('| phone | text | yes |  |  |  |');
    expect(after).toContain('- stale_note: fax');
    expect(after).not.toContain('- undocumented');

    await init(root);
    expect(await readFile(file, 'utf8')).toBe(after);
    expect(await read(root, 'db-wiki/index.md')).toContain(
      '- [public.customers](tables/public.customers.md) (table) — Everyone who has ever signed up',
    );
    // The automatic detection in the catalog is not changed by overrides.
    const catalog = JSON.parse(await read(root, '.tapu/catalog.json'));
    const cols = catalog.relations.find((r: { id: string }) => r.id === 'public.customers').columns;
    expect(cols.find((c: { name: string }) => c.name === 'phone').sensitive).toBe(true);
    expect(cols.find((c: { name: string }) => c.name === 'emailed_at').sensitive).toBe(false);
  });

  it('archives the page of a dropped relation without deleting it, and reactivates it', async () => {
    await init(root);
    const file = pagePath(root, 'public.returns.md');
    await writeFile(file, (await readFile(file, 'utf8')).replace('## Notes\n', '## Notes\n\nKeep me.\n'));
    const before = await readFile(file, 'utf8');

    await adminSql('DROP TABLE public.returns');
    const result = await init(root, { now: new Date('2026-09-25T12:00:00Z') });
    expect(result.removed).toEqual(['public.returns']);
    expect(result.pages.removed).toEqual(['public.returns']);
    expect(result.pages.updated).toEqual(['public.order_items']); // its "Referenced by" section changed

    const after = await readFile(file, 'utf8');
    expect(parsed(after, 'public.returns').state).toBe('removed');
    expect(after.replace(LIFECYCLE_WARNING.removed + '\n\n', '').replace('tapu:state removed', 'tapu:state active')).toBe(before);
    expect(await read(root, 'db-wiki/log.md')).toMatch(/12:00:00Z init: 10 relations, 4 enums; pages: 0 new, 1 changed, 1 removed, 0 out of scope, 0 skipped\n$/);
    const index = await read(root, 'db-wiki/index.md');
    expect(index).toContain('## Archived pages\n\n- [public.returns](tables/public.returns.md) — removed from the database');

    // Repeated refreshes do not duplicate the warning or change the retained content.
    await init(root);
    expect(await readFile(file, 'utf8')).toBe(after);

    await resetFixture();
    await init(root);
    const revived = await readFile(file, 'utf8');
    expect(parsed(revived, 'public.returns').state).toBe('active');
    expect(revived).not.toContain(LIFECYCLE_WARNING.removed);
    expect(revived).toContain('Keep me.');
  });

  it('marks pages outside a narrowed schema scope out_of_scope, not removed', async () => {
    await init(root, { schemas: ['public', 'billing'] });
    expect(JSON.parse(await read(root, '.tapu/config.json')).schemas).toEqual(['public', 'billing']);
    expect(await read(root, 'db-wiki/tables/billing.invoices.md')).toContain('| iban | text | yes |  | SENSITIVE |  |');
    const again = await init(root);
    expect(again.config.schemas).toEqual(['public', 'billing']);

    const narrowed = await init(root, { schemas: ['public'] });
    expect(narrowed.pages.outOfScope).toEqual(['billing.invoices']);
    expect(narrowed.pages.removed).toEqual([]);
    const page = await read(root, 'db-wiki/tables/billing.invoices.md');
    expect(parsed(page, 'billing.invoices').state).toBe('out_of_scope');
    expect(page).toContain(LIFECYCLE_WARNING.out_of_scope);
    expect(await read(root, 'db-wiki/index.md')).toContain('— outside the configured schemas');
  });

  it('reports and preserves malformed pages, still refreshes the catalog, and exits 2', async () => {
    await init(root);
    const broken: Record<string, (t: string) => string> = {
      'public.orders.md': (t) => t.replace(AUTO_END, ''),
      'public.products.md': (t) => t + `\n${AUTO_END}\n`,
      'public.returns.md': (t) => t.replace(/^---\n/, ''),
      'public.customers.md': (t) => t.replace('purpose: ""', 'purpose: ""\npurpose: "twice"'),
      'public.order_items.md': (t) => t.replace('table: public.order_items', 'table: public.orders'),
      'public.daily_sales.md': (t) => t.replace('tags: []', 'tags: 7'),
    };
    const contents = new Map<string, string>();
    for (const [name, breakIt] of Object.entries(broken)) {
      const text = breakIt(await readFile(pagePath(root, name), 'utf8'));
      await writeFile(pagePath(root, name), text);
      contents.set(name, text);
    }
    await adminSql('ALTER TABLE public.orders ADD COLUMN note text');

    const result = await runCli(['init'], root, { TAPU_DATABASE_URL: ADMIN_URL });
    expect(result.code).toBe(2);
    for (const name of Object.keys(broken)) expect(result.stdout).toContain(`Skipped db-wiki/tables/${name}`);
    expect(result.stdout).toContain('Partial refresh');
    for (const [name, text] of contents) expect(await readFile(pagePath(root, name), 'utf8')).toBe(text);
    const catalog = JSON.parse(await read(root, '.tapu/catalog.json'));
    const orders = catalog.relations.find((r: { id: string }) => r.id === 'public.orders');
    expect(orders.columns.map((c: { name: string }) => c.name)).toContain('note');
    expect(await read(root, 'db-wiki/log.md')).toMatch(/6 skipped\n$/);
  });

  it('keeps stale column notes after the column is dropped', async () => {
    await init(root);
    await setFrontmatter(
      root,
      'public.orders.md',
      'tapu: 1\ntable: public.orders\ncolumns:\n  shipping_address:\n    note: "Free text from checkout"',
    );
    await adminSql('ALTER TABLE public.orders DROP COLUMN shipping_address');
    await init(root);
    const page = await readFile(pagePath(root, 'public.orders.md'), 'utf8');
    expect(page).toContain('    note: "Free text from checkout"');
    expect(page).toContain('- stale_note: shipping_address');
  });

  it('leaves every artifact unchanged when the connection fails', async () => {
    await init(root);
    const before = await snapshot(root);
    const bad = new URL(ADMIN_URL);
    bad.port = '1';
    const result = await runCli(['init', '--db', bad.toString(), '--schemas', 'billing'], root);
    expect(result.code).toBe(2);
    expect(result.stderr).toMatch(/^tapu: Could not connect/);
    expect(await snapshot(root)).toEqual(before);
  });

  it('refuses a wiki directory that is a symbolic link before writing anything', async () => {
    const outside = await tempRoot();
    await symlink(outside, join(root, 'db-wiki'));
    await expect(init(root)).rejects.toMatchObject({ code: 'unsafe_path' });
    expect(await readdir(outside)).toEqual([]);
    expect(await listFiles(root)).toEqual([]);
  });

  it('skips a page that is a symbolic link instead of following it', async () => {
    await init(root);
    const outside = join(await tempRoot(), 'target.md');
    await writeFile(outside, 'outside\n');
    await rm(pagePath(root, 'public.orders.md'));
    await symlink(outside, pagePath(root, 'public.orders.md'));
    const result = await init(root);
    expect(result.partial).toBe(true);
    expect(result.pages.skipped[0]).toMatchObject({ file: 'db-wiki/tables/public.orders.md' });
    expect(await readFile(outside, 'utf8')).toBe('outside\n');
  });

  it('rejects an invalid config instead of overwriting it', async () => {
    await mkdir(join(root, '.tapu'));
    await writeFile(join(root, '.tapu/config.json'), '{"version":1,"schemas":["public"],"wikiDir":"../outside"}');
    await expect(init(root)).rejects.toMatchObject({ code: 'invalid_config' });
    expect(await listFiles(root)).toEqual(['.tapu/config.json']);
  });

  it('appends the AGENTS.md paragraph once with --write-agents', async () => {
    const first = await init(root);
    expect(first.agents).toBe('skipped');
    await expect(readFile(join(root, 'AGENTS.md'), 'utf8')).rejects.toThrow();

    await writeFile(join(root, 'AGENTS.md'), '# Agents\nBe nice.');
    expect((await init(root, { writeAgents: true })).agents).toBe('written');
    expect((await init(root, { writeAgents: true })).agents).toBe('present');
    expect(await read(root, 'AGENTS.md')).toBe(`# Agents\nBe nice.\n\n${AGENTS_PARAGRAPH}\n`);
  });

  it('prints a summary with counts and the AGENTS paragraph', async () => {
    const result = await runCli(['init', '--project-dir', root], '/', { TAPU_DATABASE_URL: ADMIN_URL });
    expect(result.code).toBe(0);
    expect(result.stdout).toContain('11 relations, 4 enums');
    expect(result.stdout).toContain('Pages: 11 created, 0 updated, 0 archived as removed, 0 archived as out of scope, 0 skipped');
    expect(result.stdout).toContain('9 of 11 active relations have no purpose and no DB comment');
    expect(result.stdout).toContain(AGENTS_PARAGRAPH);
    expect(await listFiles(root)).toContain('db-wiki/index.md');
  });
});
