import { mkdir, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { parseDocument, type Document } from 'yaml';
import type { Catalog, Column, Relation, RelationKind } from './catalog.js';
import { compareStrings } from './catalog.js';
import { projectPaths, readTextIfExists, writeIfChanged, type Config } from './project.js';
import { stripControlChars } from './sanitize.js';
import { relationWarnings } from './warnings.js';

export const AUTO_START = '<!-- tapu:auto:start — generated by `tapu init`, do not edit inside this block -->';
export const AUTO_END = '<!-- tapu:auto:end -->';
const AUTO_START_PREFIX = '<!-- tapu:auto:start';
const HASH_RE = /<!-- tapu:hash ([0-9a-f]+) -->/;

export const REMOVED_WARNING =
  '> **Warning:** this relation no longer exists in the database. Tapu keeps this page so nothing is lost; delete it if the removal is intended.';

export const AGENTS_LINE =
  'Before changing the database schema, run `tapu explain` and read the relevant db-wiki pages.';

// ---------------------------------------------------------------------------
// Frontmatter

export interface ColumnOverride {
  note?: string;
  sensitive?: boolean;
}

/** Normalized view of a page's frontmatter. Only `tapu`, `table` and `status: removed` are Tapu-owned. */
export interface Frontmatter {
  tapu: unknown;
  table: unknown;
  status: string | null;
  purpose: string;
  owner: string;
  tags: string[];
  columns: Record<string, ColumnOverride>;
}

function scalarText(v: unknown): string {
  return typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean' ? String(v) : '';
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

export function normalizeFrontmatter(value: unknown): Frontmatter {
  const v = isRecord(value) ? value : {};
  // Null prototype: a column entry named `__proto__` must stay an ordinary key.
  const columns: Record<string, ColumnOverride> = Object.create(null);
  if (isRecord(v.columns)) {
    for (const [name, raw] of Object.entries(v.columns)) {
      const override: ColumnOverride = {};
      if (isRecord(raw)) {
        const note = scalarText(raw.note);
        if (note) override.note = note;
        if (typeof raw.sensitive === 'boolean') override.sensitive = raw.sensitive;
      } else if (scalarText(raw)) {
        override.note = scalarText(raw);
      }
      columns[name] = override;
    }
  }
  const tags = Array.isArray(v.tags) ? v.tags.map(scalarText).filter(Boolean) : scalarText(v.tags) ? [scalarText(v.tags)] : [];
  return {
    tapu: v.tapu,
    table: v.table,
    status: scalarText(v.status) || null,
    purpose: scalarText(v.purpose),
    owner: scalarText(v.owner),
    tags,
    columns,
  };
}

/** Effective sensitivity: a frontmatter override always wins over name-based detection. */
export function isSensitive(col: Column, front: Frontmatter | null): boolean {
  return front?.columns[col.name]?.sensitive ?? col.sensitive;
}

// ---------------------------------------------------------------------------
// File names

const SAFE_CHAR = /^[A-Za-z0-9._-]$/;

/** `public.orders` -> `public.orders.md`; other characters are percent-encoded. */
export function pageFileName(id: string): string {
  let out = '';
  for (const ch of id) {
    if (SAFE_CHAR.test(ch)) out += ch;
    else for (const b of Buffer.from(ch, 'utf8')) out += '%' + b.toString(16).toUpperCase().padStart(2, '0');
  }
  return out + '.md';
}

export function pageIdFromFileName(file: string): string | null {
  if (!file.endsWith('.md')) return null;
  try {
    const id = decodeURIComponent(file.slice(0, -3));
    return id && pageFileName(id) === file ? id : null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Parsing

export interface ParsedPage {
  text: string;
  doc: Document;
  front: Frontmatter;
  /** Offsets of the YAML text between the `---` lines. */
  fmStart: number;
  fmEnd: number;
  /** Offsets of the content between the start-marker line and the end marker. */
  autoStart: number;
  autoEnd: number;
  /** Hash of the relation the auto block was last generated from. */
  hash: string | null;
  /** Free text after the auto block (human-written). */
  notes: string;
}

export type PageParse = { ok: true; page: ParsedPage } | { ok: false; reason: string };

function indexesOf(text: string, needle: string, from: number): number[] {
  const out: number[] = [];
  for (let i = text.indexOf(needle, from); i !== -1; i = text.indexOf(needle, i + needle.length)) out.push(i);
  return out;
}

function lineAt(text: string, start: number): { line: string; next: number } {
  const nl = text.indexOf('\n', start);
  const end = nl === -1 ? text.length : nl;
  return { line: text.slice(start, end).replace(/\r$/, ''), next: nl === -1 ? -1 : nl + 1 };
}

export function parsePage(text: string): PageParse {
  const fail = (reason: string): PageParse => ({ ok: false, reason });

  const first = lineAt(text, 0);
  if (first.line !== '---' || first.next === -1) return fail('missing frontmatter');
  const fmStart = first.next;
  let fmEnd = -1;
  let bodyStart = -1;
  for (let pos = fmStart; pos !== -1; ) {
    const { line, next } = lineAt(text, pos);
    if (line === '---') {
      fmEnd = pos;
      bodyStart = next === -1 ? text.length : next;
      break;
    }
    pos = next;
  }
  if (fmEnd === -1) return fail('unterminated frontmatter');

  const doc = parseDocument(text.slice(fmStart, fmEnd));
  if (doc.errors.length > 0) return fail('frontmatter is not valid YAML');
  const value: unknown = doc.toJS();
  if (value !== null && value !== undefined && !isRecord(value)) return fail('frontmatter is not a mapping');

  const starts = indexesOf(text, AUTO_START_PREFIX, bodyStart);
  const ends = indexesOf(text, AUTO_END, bodyStart);
  if (starts.length !== 1 || ends.length !== 1) return fail('tapu:auto markers are missing or duplicated');
  const s = starts[0]!;
  const e = ends[0]!;
  if (text[s - 1] !== '\n' || text[e - 1] !== '\n') return fail('tapu:auto markers must start a line');
  const startLine = lineAt(text, s);
  if (!startLine.line.endsWith('-->') || startLine.next === -1 || startLine.next > e) {
    return fail('tapu:auto markers are malformed');
  }

  const auto = text.slice(startLine.next, e);
  return {
    ok: true,
    page: {
      text,
      doc,
      front: normalizeFrontmatter(value),
      fmStart,
      fmEnd,
      autoStart: startLine.next,
      autoEnd: e,
      hash: HASH_RE.exec(auto)?.[1] ?? null,
      notes: text.slice(e + AUTO_END.length).trim(),
    },
  };
}

// ---------------------------------------------------------------------------
// Rendering

export interface RenderContext {
  enums: Map<string, string[]>;
  /** Relation ids that have a page (link targets). */
  known: Set<string>;
}

export function renderContext(catalog: Catalog): RenderContext {
  return {
    enums: new Map(catalog.enums.map((e) => [e.id, e.values])),
    known: new Set(catalog.relations.map((r) => r.id)),
  };
}

/** Escapes text for one line of generated markdown. `<` is escaped so no text can forge a marker. */
export function mdText(s: string): string {
  return stripControlChars(s).replace(/\n/g, ' ').replace(/</g, '&lt;').replace(/\|/g, '\\|');
}

function link(id: string, ctx: RenderContext, prefix = ''): string {
  if (!ctx.known.has(id)) return mdText(id);
  return `[${mdText(id)}](${prefix}${encodeURIComponent(pageFileName(id))})`;
}

const KIND_LABEL: Record<RelationKind, string> = {
  table: 'table',
  partitioned_table: 'partitioned table',
  view: 'view',
  materialized_view: 'materialized view',
};

function columnFlags(rel: Relation, col: Column, front: Frontmatter | null): string[] {
  const flags: string[] = [];
  if (rel.primaryKey?.columns.includes(col.name)) flags.push('PK');
  if (rel.foreignKeys.some((fk) => fk.columns.includes(col.name))) flags.push('FK');
  if (rel.uniques.some((u) => u.columns.length === 1 && u.columns[0] === col.name)) flags.push('UNIQUE');
  if (col.identity === 'always') flags.push('IDENTITY ALWAYS');
  if (col.identity === 'by_default') flags.push('IDENTITY BY DEFAULT');
  if (col.generated !== null) flags.push('GENERATED');
  if (isSensitive(col, front)) flags.push('SENSITIVE');
  return flags;
}

/** Content between the auto markers (starts with the hash comment, ends with a blank line). */
export function renderAuto(rel: Relation, front: Frontmatter | null, ctx: RenderContext): string {
  const lines: string[] = [`<!-- tapu:hash ${rel.hash} -->`, ''];
  lines.push(
    `**Kind:** ${KIND_LABEL[rel.kind]} · **Estimated rows:** ${rel.rows === null ? 'unknown' : String(rel.rows)}`,
    '',
  );
  if (rel.comment) lines.push(`**Comment:** ${mdText(rel.comment)}`, '');

  lines.push('### Columns', '', '| Column | Type | Null | Default | Flags | Comment |', '| --- | --- | --- | --- | --- | --- |');
  for (const col of rel.columns) {
    const values = col.enumType ? ctx.enums.get(col.enumType) : undefined;
    const type = values ? `${col.type} (${values.join(', ')})` : col.type;
    const def = col.generated !== null ? `generated: ${col.generated}` : (col.default ?? '');
    const cells = [col.name, type, col.nullable ? 'yes' : 'no', def, columnFlags(rel, col, front).join(', '), col.comment ?? ''];
    lines.push(`| ${cells.map(mdText).join(' | ')} |`);
  }
  lines.push('');

  if (rel.primaryKey && rel.primaryKey.columns.length > 1) {
    lines.push(`**Primary key:** (${mdText(rel.primaryKey.columns.join(', '))})`, '');
  }
  const multiUniques = rel.uniques.filter((u) => u.columns.length > 1);
  if (multiUniques.length > 0) {
    lines.push('### Unique constraints', '');
    for (const u of multiUniques) lines.push(`- ${mdText(u.name)}: (${mdText(u.columns.join(', '))})`);
    lines.push('');
  }

  if (rel.foreignKeys.length > 0) {
    lines.push('### Foreign keys', '');
    for (const fk of rel.foreignKeys) {
      lines.push(
        `- ${mdText(fk.columns.join(', '))} → ${link(fk.refTable, ctx)} (${mdText(fk.refColumns.join(', '))}), on delete ${fk.onDelete} — ${mdText(fk.name)}`,
      );
    }
    lines.push('');
  }

  if (rel.referencedBy.length > 0) {
    lines.push('### Referenced by', '');
    for (const ref of rel.referencedBy) {
      lines.push(`- ${link(ref.table, ctx)} (${mdText(ref.columns.join(', '))}) — ${mdText(ref.name)}`);
    }
    lines.push('');
  }

  if (rel.indexes.length > 0) {
    lines.push('### Indexes', '');
    for (const ix of rel.indexes) lines.push(`- ${mdText(ix.definition)}`);
    lines.push('');
  }

  if (rel.checks.length > 0) {
    lines.push('### Checks', '');
    for (const c of rel.checks) lines.push(`- ${mdText(c.name)}: ${mdText(c.definition)}`);
    lines.push('');
  }

  const warnings = relationWarnings(rel, front);
  if (warnings.length > 0) {
    lines.push('### Warnings', '');
    for (const w of warnings) lines.push(`- ${mdText(w)}`);
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

function yamlScalar(s: string): string {
  return /^[A-Za-z_][A-Za-z0-9_.-]*$/.test(s) ? s : JSON.stringify(s);
}

export function renderNewPage(rel: Relation, ctx: RenderContext): string {
  return [
    '---',
    'tapu: 1',
    `table: ${yamlScalar(rel.id)}`,
    'purpose: "" # one line, human-owned',
    'owner: "" # human-owned',
    'tags: []',
    'columns: # human-owned notes and overrides, keyed by column name',
    '  # some_column:',
    '  #   note: "Why this column exists"',
    '  #   sensitive: true',
    '---',
    '',
    `# ${mdText(rel.id)}`,
    '',
    AUTO_START,
    renderAuto(rel, null, ctx) + AUTO_END,
    '',
    '## Why it exists',
    '',
    '_Not documented yet. What does this table represent, who depends on it, what breaks if it changes?_',
    '',
    '## Notes',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Merging

export type PageUpdate = { ok: true; text: string } | { ok: false; reason: string };

function splice(text: string, edits: { start: number; end: number; insert: string }[]): string {
  let out = text;
  for (const e of [...edits].sort((a, b) => b.start - a.start)) {
    out = out.slice(0, e.start) + e.insert + out.slice(e.end);
  }
  return out;
}

/** Returns new frontmatter text if a Tapu-owned key needs fixing, or null to keep it byte for byte. */
function fixOwnedKeys(page: ParsedPage, id: string, removed: boolean): string | null {
  const fm = page.text.slice(page.fmStart, page.fmEnd);
  const f = page.front;
  const statusOk = removed ? f.status === 'removed' : f.status !== 'removed';
  if (f.tapu === 1 && f.table === id && statusOk) return null;

  // Prefer minimal line edits so human formatting and comments stay untouched.
  if (f.tapu === 1 && f.table === id) {
    const candidate = removed
      ? page.doc.has('status')
        ? null
        : fm + 'status: removed\n'
      : fm.replace(/^status:[ \t]*["']?removed["']?[ \t]*(#.*)?(\r?\n|$)/m, '');
    if (candidate !== null) {
      const check = parseDocument(candidate);
      if (check.errors.length === 0 && normalizeFrontmatter(check.toJS()).status === (removed ? 'removed' : null)) {
        return candidate;
      }
    }
  }

  const doc = page.doc.clone();
  doc.set('tapu', 1);
  doc.set('table', id);
  if (removed) doc.set('status', 'removed');
  else if (f.status === 'removed') doc.delete('status');
  return String(doc);
}

/** Regenerates the auto block of an existing page for a live relation. */
export function updatePage(text: string, rel: Relation, ctx: RenderContext): PageUpdate {
  const parsed = parsePage(text);
  if (!parsed.ok) return parsed;
  const page = parsed.page;
  const edits = [{ start: page.autoStart, end: page.autoEnd, insert: renderAuto(rel, page.front, ctx) }];
  const fm = fixOwnedKeys(page, rel.id, false);
  if (fm !== null) edits.push({ start: page.fmStart, end: page.fmEnd, insert: fm });
  return { ok: true, text: splice(text, edits) };
}

/** Marks the page of a relation that no longer exists. The last generated content is kept. */
export function markPageRemoved(text: string, id: string): PageUpdate {
  const parsed = parsePage(text);
  if (!parsed.ok) return parsed;
  const page = parsed.page;
  const edits: { start: number; end: number; insert: string }[] = [];
  if (!text.slice(page.autoStart, page.autoEnd).startsWith(REMOVED_WARNING)) {
    edits.push({ start: page.autoStart, end: page.autoStart, insert: REMOVED_WARNING + '\n\n' });
  }
  const fm = fixOwnedKeys(page, id, true);
  if (fm !== null) edits.push({ start: page.fmStart, end: page.fmEnd, insert: fm });
  return { ok: true, text: splice(text, edits) };
}

// ---------------------------------------------------------------------------
// Reading and writing the wiki

export interface PageFile {
  id: string;
  file: string;
  path: string;
  text: string;
  parse: PageParse;
}

/** All pages under `<wikiDir>/tables`, sorted by relation id. */
export async function readPages(root: string, config: Config): Promise<Map<string, PageFile>> {
  const dir = projectPaths(root, config).tablesDir;
  let files: string[];
  try {
    files = await readdir(dir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return new Map();
    throw err;
  }
  const pages: PageFile[] = [];
  for (const file of files) {
    const id = pageIdFromFileName(file);
    if (id === null) continue;
    const path = join(dir, file);
    const text = await readTextIfExists(path);
    if (text === null) continue;
    pages.push({ id, file, path, text, parse: parsePage(text) });
  }
  pages.sort((a, b) => compareStrings(a.id, b.id));
  return new Map(pages.map((p) => [p.id, p]));
}

export function pageRelPath(config: Config, file: string): string {
  return `${config.wikiDir}/tables/${file}`;
}

export const RULES_TEMPLATE = `# Database rules

Conventions for this database. Tapu creates this file once and never overwrites it; edit it freely.

## Naming

- _Not documented yet. Example: tables are plural snake_case; foreign keys are named \`<singular>_id\`._

## Migrations

- _Not documented yet. Example: every foreign key gets an index; destructive changes ship in two steps._
`;

function renderIndex(catalog: Catalog, fronts: Map<string, Frontmatter | null>, ctx: RenderContext): string {
  const lines = [
    '# Database wiki',
    '',
    'Generated by `tapu init`: one line per relation. Set a purpose in each page’s frontmatter.',
    '',
  ];
  for (const rel of catalog.relations) {
    const purpose = fronts.get(rel.id)?.purpose.trim() || rel.comment?.trim() || '';
    lines.push(`- ${link(rel.id, ctx, 'tables/')} — ${purpose ? mdText(purpose) : '_undocumented_'}`);
  }
  return lines.join('\n') + '\n';
}

export interface WikiResult {
  created: string[];
  updated: string[];
  markedRemoved: string[];
  skipped: { file: string; reason: string }[];
}

/** Writes pages, index.md and (once) rules.md for a freshly introspected catalog. */
export async function writeWiki(root: string, config: Config, catalog: Catalog): Promise<WikiResult> {
  const paths = projectPaths(root, config);
  await mkdir(paths.tablesDir, { recursive: true });
  const pages = await readPages(root, config);
  const ctx = renderContext(catalog);
  const result: WikiResult = { created: [], updated: [], markedRemoved: [], skipped: [] };
  const fronts = new Map<string, Frontmatter | null>();

  for (const rel of catalog.relations) {
    const page = pages.get(rel.id);
    if (!page) {
      await writeIfChanged(join(paths.tablesDir, pageFileName(rel.id)), renderNewPage(rel, ctx));
      result.created.push(rel.id);
      continue;
    }
    const update = updatePage(page.text, rel, ctx);
    if (!update.ok) {
      result.skipped.push({ file: pageRelPath(config, page.file), reason: update.reason });
      continue;
    }
    fronts.set(rel.id, page.parse.ok ? page.parse.page.front : null);
    if (await writeIfChanged(page.path, update.text)) result.updated.push(rel.id);
  }

  const live = new Set(catalog.relations.map((r) => r.id));
  for (const page of pages.values()) {
    if (live.has(page.id)) continue;
    const update = markPageRemoved(page.text, page.id);
    if (!update.ok) {
      result.skipped.push({ file: pageRelPath(config, page.file), reason: update.reason });
      continue;
    }
    if (await writeIfChanged(page.path, update.text)) result.markedRemoved.push(page.id);
  }

  await writeIfChanged(paths.index, renderIndex(catalog, fronts, ctx));
  if ((await readTextIfExists(paths.rules)) === null) await writeIfChanged(paths.rules, RULES_TEMPLATE);
  return result;
}
